### ISSUE TITLE
Errors while loading a rst file

### ISSUE THREAD

**Issue by konradkam85** [pyansys/pydpf-core#222]
Hi,
I am getting an error while loading the RST file.
I load the file with the code:

`
from ansys.dpf import post
r = post.load_solution("beam.rst")
`

and I get the following error messages:

PS C:\Users\Konrad\python_basics\pyapdl> python .\pyansys_post.py
Traceback (most recent call last):
  File "C:\Users\Konrad\python_basics\pyapdl\pyansys_post.py", line 3, in <module>
    r = post.load_solution("beam.rst")
  File "C:\Users\Konrad\AppData\Local\Programs\Python\Python39\lib\site-packages\ansys\dpf\post\post_utility.py", line 33, in load_solution
    _model = Model(data_sources)
  File "C:\Users\Konrad\AppData\Local\Programs\Python\Python39\lib\site-packages\ansys\dpf\core\model.py", line 48, in __init__
    self._metadata = Metadata(data_sources, self._server)
  File "C:\Users\Konrad\AppData\Local\Programs\Python\Python39\lib\site-packages\ansys\dpf\core\model.py", line 228, in __init__
    self._set_data_sources(data_sources)
  File "C:\Users\Konrad\AppData\Local\Programs\Python\Python39\lib\site-packages\ansys\dpf\core\model.py", line 355, in _set_data_sources
    self._cache_streams_provider()
  File "C:\Users\Konrad\AppData\Local\Programs\Python\Python39\lib\site-packages\ansys\dpf\core\model.py", line 252, in _cache_streams_provider
    self._stream_provider.inputs.connect(self._data_sources)
AttributeError: 'NoneType' object has no attribute 'connect'

The beam.rst file is in the same dir as the python script.

I autumn 2021 I used this code successfully with ANSYS 2021R2.
Like a month ago I updated ANSYS to 2022R1. However, I suppose that this is rather not a reason of the problem.

After I got the error I reinstalled the library with the code `pip install ansys-dpf-post` but this did not help.

Could you advice what may be wrong?

Best,
Konrad

**Comment by rlagha** [comment]
Hi @konradkam85 ,
it looks like a mismatch in the versions of the packages. please could you : pip uninstall ansys.grpc.dpf and pip uninstall ansys.dpf.core, then pip install ansys.dpf.core

**Comment by konradkam85** [comment]
Thank you @rlagha !
Now it works :)
