### ISSUE TITLE
2022R2 and pydpf-core==0.5.2b0 incompatibility

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pydpf-core#369]
Seems that 2022R2 and `pydpf-core==0.5.2b0` are not compatible:

```
>>>  model = dpf.Model(examples.simple_bar)
ImportWarning: An incompatibility has been detected between the DPF server version (4.0 from Ansys 2022R2) and the ansys-grpc-dpf version installed (0.4.0). Please consider using the latest DPF server available in the 2022R1 Ansys unified install.
To follow the compatibility guidelines given in https://dpfdocs.pyansys.com/getting_started/index.html#client-server-compatibility while still using DPF server 4.0, please install version >=0.5.0 of ansys-grpc-dpf with the command: 
     pip install ansys-grpc-dpf>=0.5.0

>>> dpf.__version__
>>> '0.5.2b0'
```

A few things:
- `ImportWarning` is not a great error. Instead, consider subclassing `RuntimeError` with `DPFServerVersionError(RuntimeError)`
- This error isn't picking up on the right locally installed version of `ansys-dpf-core` as seen above.

**Comment by PProfizi** [comment]
Hi @akaszynski , it seems the problem might come from the version of the **ansys-grpc-dpf** package you have installed. It has been upgraded too.
What you are comparing is the error message saying grpc-dpf >=0.5.0 is required, which is true for dpf-core 0.5.2b0.

Could you please check the version of ansys-grpc-dpf installed?

The remark about the errors is noted though.

**Comment by akaszynski** [comment]
> What you are comparing is the error message saying grpc-dpf >=0.5.0 is required, which is true for dpf-core 0.5.2b0.

Good point. I'm not on a stable version, so it makes sense that 0.5.2b0 < 0.5.0

Error message still needs to be fixed.

**Comment by PProfizi** [comment]
Sorry, my explanation might not have been the best: 
0.5.2b0 is for ansys-dpf-core, and the ">=0.5.0" in the error is a criterion on ansys-grpc-dpf. 
I do not see where it compares them and 0.5.2b0 < 0.5.0, which should never be true. 
Basically ansys-grpc-dpf >= 0.5.0 is a requirement for any ansys-dpf-core >= 0.5.0, thus including 0.5.2b0.

**Comment by akaszynski** [comment]
I think beta releases are considered stable releases in semantic versioning. Either way, 0.5.2b0 isn't working on my end with 2022R2.

**Comment by PProfizi** [comment]
@akaszynski Could you share the list of installed packages in your environment? Did you start one from scratch to install 0.5.2b0 in it?

**Comment by akaszynski** [comment]
Good and bad news. Problem solved by a fresh virtual enviornment:

```
cd /tmp
python -m venv .venv
source .venv/bin/activate
pip install wheel
cd ~/ansys/source/pydpf-core/
git checkout 0.5.2b1
pip install -e .
cd ~/Downloads/
python 00-basic_example.py 
```

Now for the bad news: there's an issue with running the tests:
```
cd ~/ansys/source/pydpf-core/
pip install -r requirements/requirements_test.txt 
pytest -vx
```

```
/home/alex/ansys/source/pydpf-core/ansys/dpf/core/server_types.py:862: UserWarning: Traceback (most recent call last):
  File "/home/alex/ansys/source/pydpf-core/ansys/dpf/core/server_types.py", line 850, in shutdown
    self._shutdown_func[0](self._shutdown_func[1])
  File "/tmp/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/tmp/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "{"created":"@1659587557.868850645","description":"Error received from peer ipv4:127.0.0.1:50054","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"","grpc_status":12}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/ansys/source/pydpf-core/ansys/dpf/core/server_types.py", line 858, in shutdown
    p = psutil.Process(self.info["server_process_id"])
  File "/tmp/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/tmp/.venv/lib/python3.8/site-packages/psutil/__init__.py", line 355, in _init
    self._proc = _psplatform.Process(pid)
  File "/tmp/.venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1665, in __init__
    self._procfs_path = get_procfs_path()
  File "/tmp/.venv/lib/python3.8/site-packages/psutil/_common.py", line 800, in get_procfs_path
    return sys.modules['psutil'].PROCFS_PATH
KeyError: 'psutil'
```


Full environment from `pip list`
```
Package                               Version   Editable project location
------------------------------------- --------- ----------------------------------
aiohttp                               3.8.1
aiosignal                             1.2.0
ansys-api-platform-instancemanagement 1.0.0b3
ansys-dpf-core                        0.5.2b1   /home/alex/ansys/source/pydpf-core
ansys-dpf-gate                        0.1.1
ansys-grpc-dpf                        0.5.1
ansys-platform-instancemanagement     1.0.2
appdirs                               1.4.4
asttokens                             2.0.5
async-timeout                         4.0.2
attrs                                 22.1.0
autobahn                              22.7.1
Automat                               20.2.0
backcall                              0.2.0
cachetools                            5.2.0
certifi                               2022.6.15
cffi                                  1.15.1
charset-normalizer                    2.1.0
constantly                            15.1.0
coverage                              6.4.2
cryptography                          37.0.4
cycler                                0.11.0
decorator                             5.1.1
executing                             0.8.3
flake8                                5.0.4
fonttools                             4.34.4
frozenlist                            1.3.1
google-api-core                       2.8.2
google-api-python-client              2.55.0
google-auth                           2.9.1
google-auth-httplib2                  0.1.0
googleapis-common-protos              1.56.4
grpcio                                1.47.0
httplib2                              0.20.4
hyperlink                             21.0.0
idna                                  3.3
imageio                               2.21.0
importlib-metadata                    4.12.0
incremental                           21.3.0
iniconfig                             1.1.1
ipython                               8.4.0
jedi                                  0.18.1
kiwisolver                            1.4.4
matplotlib                            3.5.2
matplotlib-inline                     0.1.3
mccabe                                0.7.0
multidict                             6.0.2
numpy                                 1.23.1
packaging                             21.3
parso                                 0.8.3
pexpect                               4.8.0
pickleshare                           0.7.5
Pillow                                9.2.0
pip                                   22.2.2
pluggy                                1.0.0
prompt-toolkit                        3.0.30
protobuf                              3.20.1
protoc-gen-swagger                    0.1.0
psutil                                5.9.1
ptyprocess                            0.7.0
pure-eval                             0.2.2
py                                    1.11.0
pyasn1                                0.4.8
pyasn1-modules                        0.2.8
pycodestyle                           2.9.1
pycparser                             2.21
pyflakes                              2.5.0
Pygments                              2.12.0
pyparsing                             3.0.9
pytest                                7.1.2
pytest-cov                            3.0.0
pytest-rerunfailures                  10.2
python-dateutil                       2.8.2
pyvista                               0.35.2
requests                              2.28.1
rsa                                   4.9
scooby                                0.6.0
setuptools                            56.0.0
six                                   1.16.0
stack-data                            0.3.0
tomli                                 2.0.1
tqdm                                  4.64.0
traitlets                             5.3.0
Twisted                               22.4.0
txaio                                 22.2.1
typing_extensions                     4.3.0
uritemplate                           4.1.1
urllib3                               1.26.11
vtk                                   9.0.3
wcwidth                               0.2.5
wheel                                 0.37.1
wslink                                1.6.6
yarl                                  1.8.1
zipp                                  3.8.1
zope.interface                        5.4.0
```

**Comment by PProfizi** [comment]
Hi @akaszynski, is this still relevant?

**Comment by PProfizi** [comment]
Closing as stale, please reopen if still relevant.
