### ISSUE TITLE
Error because calling error arguments

### ISSUE THREAD

**Issue by germa89** [pyansys/pydpf-core#912]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When raising an error accidentally we "call" the error arguments:

```pycon

Unexpected failing examples:
/home/runner/work/pymapdl/pymapdl/examples/00-mapdl-examples/basic_dpf_example.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/runner/work/pymapdl/pymapdl/examples/00-mapdl-examples/basic_dpf_example.py", line 63, in <module>
    print(model)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 202, in __str__
    txt += str(self.results)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 156, in results
    self.metadata.result_info,
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 101, in wrapper
    out = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 481, in result_info
    self._cache_result_info()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 280, in _cache_result_info
    self._result_info = self._load_result_info()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/dpf/core/model.py", line 419, in _load_result_info
    if "results file is not defined in the Data sources" in e.args():
TypeError: 'tuple' object is not callable
```

From:
https://github.com/pyansys/pymapdl/actions/runs/4767243846/jobs/8475271981?pr=2008#step:16:401

### Steps To Reproduce

Running ``basic_dpf_example`` file

### Which Operating System are you using?

Windows

### Which DPF/Ansys version are you using?

DPF Server as standalone

### Which Python version are you using?

3.7

### Installed packages

NA

**Comment by germa89** [comment]
Closing because it is fixed in the master branch. #Sorry
